# Generated by Django 4.0.1 on 2022-03-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20220311_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='email',
        ),
    ]
