# Generated by Django 3.2.5 on 2022-03-14 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_user1_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
