# Generated by Django 3.2.5 on 2022-03-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_user1_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Random',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranvc', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user1',
            name='email',
        ),
    ]
