# Generated by Django 3.2.5 on 2022-03-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20220315_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Random',
        ),
    ]
