# Generated by Django 3.2.5 on 2022-03-16 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20220316_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='email',
        ),
        migrations.AddField(
            model_name='user1',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
