# Generated by Django 3.2.5 on 2022-03-16 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20220316_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user1',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user1',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
